#!/usr/bin/env python3
"""Generate tokens/tokens.css from tokens/tokens.json (the single source of truth)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
tokens = json.loads((ROOT / "tokens" / "tokens.json").read_text())

lines = [
    "/* GENERATED by scripts/build_tokens.py from tokens/tokens.json. Do not edit by hand. */",
    ":root {",
]
for name, c in tokens["colour"].items():
    lines.append(f"  --sol-colour-{name}: {c['hex']};")
lines.append(f"  --sol-font-family: '{tokens['type']['family']}', {tokens['type']['fallback']};")
for name, t in tokens["type"]["scale"].items():
    lines.append(f"  --sol-text-{name}-size: {t['size']}px;")
    lines.append(f"  --sol-text-{name}-line: {t['line']}px;")
    lines.append(f"  --sol-text-{name}-weight: {t['weight']};")
for i, s in enumerate(tokens["space"], start=1):
    lines.append(f"  --sol-space-{i}: {s}px;")
for name, r in tokens["radius"].items():
    lines.append(f"  --sol-radius-{name}: {r}px;")
lines.append(f"  --sol-touch-target-min: {tokens['touch_target_min']}px;")
lines.append("}")

out = ROOT / "tokens" / "tokens.css"
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out.relative_to(ROOT)}")
